(() => {
  'use strict';
  const APP_VERSION = '1.2.0';
  const DB_NAME = 'multigestion_mr_v1';
  const DB_VERSION = 2;
  const $ = id => document.getElementById(id);
  let db, businesses = [], movements = [], smartMemory = [];
  let activeBusinessId = null, editingMovementId = null, smartField = null;
  const money = new Intl.NumberFormat('es-SV', { style: 'currency', currency: 'USD' });
  const today = new Date();

  $('date').value = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
  const logo = $('brandLogo');
  if (logo?.src) document.documentElement.style.setProperty('--watermark-logo', `url("${logo.src}")`);
  $('versionPill').textContent = `V${APP_VERSION.replace(/\.0$/,'')}`;

  function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('businesses'))d.createObjectStore('businesses',{keyPath:'id'});if(!d.objectStoreNames.contains('movements')){const s=d.createObjectStore('movements',{keyPath:'id'});s.createIndex('businessId','businessId',{unique:false});}if(!d.objectStoreNames.contains('smartMemory')){const s=d.createObjectStore('smartMemory',{keyPath:'id'});s.createIndex('businessId','businessId',{unique:false});s.createIndex('field','field',{unique:false});}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
  function getAll(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);})}
  function put(name,value){return new Promise((res,rej)=>{const r=store(name,'readwrite').put(value);r.onsuccess=()=>res(value);r.onerror=()=>rej(r.error);})}
  function remove(name,id){return new Promise((res,rej)=>{const r=store(name,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);})}
  function uid(prefix){return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
  function normalize(v){return String(v||'').trim().replace(/\s+/g,' ')}
  function memoryKey(v){return normalize(v).toLocaleLowerCase('es')}
  function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2500)}
  function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function cap(s){s=String(s||'');return s? s.charAt(0).toUpperCase()+s.slice(1):''}
  function fmtNum(n){return Number(n||0).toLocaleString('es-SV',{maximumFractionDigits:2})}
  function isExpense(m){return m.type==='gasto'||m.type==='compra'}
  function isIncome(m){return m.type==='ingreso'||m.type==='venta'}
  function calc(list){const income=list.filter(isIncome).reduce((s,m)=>s+Number(m.total||0),0);const expense=list.filter(isExpense).reduce((s,m)=>s+Number(m.total||0),0);return{income,expense,profit:income-expense}}
  function businessMovements(id=activeBusinessId){return id?movements.filter(m=>m.businessId===id):[]}

  async function refresh(){businesses=await getAll('businesses');movements=await getAll('movements');smartMemory=await getAll('smartMemory');businesses.sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));if(activeBusinessId&&!businesses.some(b=>b.id===activeBusinessId))activeBusinessId=null;render();}

  function render(){
    const active=businesses.find(b=>b.id===activeBusinessId);const list=active?businessMovements(active.id):[];const c=calc(list);const general=calc(movements);
    const hint=active?active.name:'Sin negocio seleccionado';
    $('metricBusinessTitle').textContent=active?active.name:'Seleccione un negocio';
    $('mIncome').textContent=money.format(c.income);$('mExpense').textContent=money.format(c.expense);$('mProfit').textContent=money.format(c.profit);$('mMovements').textContent=list.length;
    $('mIncomeHint').textContent=hint;$('mExpenseHint').textContent=hint;$('mProfitHint').textContent=hint;
    $('gBusinesses').textContent=businesses.length;$('gIncome').textContent=money.format(general.income);$('gExpense').textContent=money.format(general.expense);$('gProfit').textContent=money.format(general.profit);
    $('businessList').innerHTML='';$('emptyBusinesses').hidden=businesses.length>0;
    businesses.forEach(b=>{const own=businessMovements(b.id),ownCalc=calc(own);const btn=document.createElement('button');btn.type='button';btn.className='business-item'+(b.id===activeBusinessId?' active':'');btn.innerHTML=`<span class="business-dot"></span><span><strong>${escapeHtml(b.name)}</strong><small>${escapeHtml(b.type)} · ${own.length} movimientos · Resultado ${money.format(ownCalc.profit)}</small></span>`;btn.addEventListener('click',()=>{if(editingMovementId&&!confirm('Hay un registro en edición. ¿Cambiar de negocio y cancelar la edición?'))return;cancelEditing(false);activeBusinessId=b.id;render();});$('businessList').appendChild(btn);});
    const enabled=!!active;$('exportBtn').disabled=!enabled;$('deleteBusinessBtn').disabled=!enabled;$('saveMovementBtn').disabled=!enabled;
    $('activeBusinessName').textContent=active?active.name:'Ninguno seleccionado';$('activeBusinessType').textContent=active?`${active.type}${active.description?' · '+active.description:''}`:'Cree o seleccione un negocio para comenzar.';
    $('bIncome').textContent=money.format(c.income);$('bExpense').textContent=money.format(c.expense);$('bProfit').textContent=money.format(c.profit);$('bMovements').textContent=list.length;
    renderMovements(list);
  }

  function renderMovements(baseList){const filter=$('filterType').value,q=$('searchMovement').value.trim().toLowerCase();const list=baseList.filter(m=>(filter==='todos'||m.type===filter)&&(!q||`${m.category} ${m.concept} ${m.party||''} ${m.notes||''}`.toLowerCase().includes(q))).sort((a,b)=>String(b.date).localeCompare(String(a.date))||(b.createdAt||0)-(a.createdAt||0));$('movementRows').innerHTML='';$('emptyMovements').hidden=list.length>0;list.forEach(m=>{const tr=document.createElement('tr');if(m.id===editingMovementId)tr.classList.add('editing-row');tr.innerHTML=`<td>${escapeHtml(m.date)}</td><td><span class="type-chip type-${escapeHtml(m.type)}">${escapeHtml(cap(m.type))}</span></td><td>${escapeHtml(m.category)}</td><td>${escapeHtml(m.concept)}</td><td>${fmtNum(m.quantity)}</td><td>${escapeHtml(m.unit)}</td><td><strong>${money.format(Number(m.total||0))}</strong></td><td>${escapeHtml(m.paymentMethod||'')}</td><td class="row-actions"><button class="mini-btn edit" type="button" data-action="edit">✏️ Editar</button><button class="mini-btn save" type="button" data-action="save" ${m.id===editingMovementId?'':'disabled'}>💾 Guardar</button><button class="mini-btn delete" type="button" data-action="delete">🗑️ Eliminar</button></td>`;tr.querySelector('[data-action="edit"]').addEventListener('click',()=>startEditing(m.id));tr.querySelector('[data-action="save"]').addEventListener('click',()=>saveEditedMovement(m.id));tr.querySelector('[data-action="delete"]').addEventListener('click',()=>deleteMovement(m.id));$('movementRows').appendChild(tr);});}

  function updateTotal(){const q=Math.max(0,Number($('quantity').value)||0),p=Math.max(0,Number($('unitPrice').value)||0);$('total').value=(q*p).toFixed(2)}
  function movementFromForm(existing=null){const quantity=Math.max(0,Number($('quantity').value)||0),unitPrice=Math.max(0,Number($('unitPrice').value)||0);const m={id:existing?.id||uid('mov'),businessId:existing?.businessId||activeBusinessId,date:$('date').value,type:$('movementType').value,category:normalize($('category').value),concept:normalize($('concept').value),quantity,unit:$('unit').value,unitPrice,total:Number((quantity*unitPrice).toFixed(2)),party:normalize($('party').value),paymentMethod:$('paymentMethod').value,notes:normalize($('notes').value),createdAt:existing?.createdAt||Date.now(),updatedAt:existing?Date.now():undefined};if(!m.date||!m.category||!m.concept)return{error:'Complete los campos obligatorios'};if(quantity<=0)return{error:'La cantidad debe ser mayor que 0'};return{movement:m};}
  function resetMovementForm(){const keepDate=$('date').value;$('movementForm').reset();$('date').value=keepDate||new Date().toISOString().slice(0,10);$('quantity').value='1';$('total').value='0.00';$('movementType').value='gasto';$('unit').value='unidad';$('paymentMethod').value='Efectivo';}
  function startEditing(id){const m=movements.find(x=>x.id===id&&x.businessId===activeBusinessId);if(!m)return;editingMovementId=id;$('date').value=m.date;$('movementType').value=m.type;$('category').value=m.category;$('concept').value=m.concept;$('quantity').value=m.quantity;$('unit').value=m.unit;$('unitPrice').value=m.unitPrice;$('total').value=Number(m.total||0).toFixed(2);$('party').value=m.party||'';$('paymentMethod').value=m.paymentMethod||'Efectivo';$('notes').value=m.notes||'';$('movementFormTitle').textContent='Editar movimiento';$('editBadge').hidden=false;$('cancelEditBtn').hidden=false;$('saveMovementBtn').textContent='💾 Guardar cambios';renderMovements(businessMovements());$('movementForm').scrollIntoView({behavior:'smooth',block:'start'});toast('Registro cargado completo para editar');}
  function cancelEditing(show=true){if(!editingMovementId&&$('editBadge').hidden)return;editingMovementId=null;$('movementFormTitle').textContent='Registrar movimiento';$('editBadge').hidden=true;$('cancelEditBtn').hidden=true;$('saveMovementBtn').textContent='💾 Guardar movimiento';resetMovementForm();if(show)toast('Edición cancelada');}
  async function rememberMovement(m){for(const [field,value] of [['category',m.category],['concept',m.concept],['party',m.party]]){const clean=normalize(value);if(!clean)continue;const key=memoryKey(clean);const id=`${m.businessId}|${field}|${key}`;const existing=smartMemory.find(x=>x.id===id);await put('smartMemory',{id,businessId:m.businessId,field,key,value:existing?.value||clean,createdAt:existing?.createdAt||Date.now(),lastUsedAt:Date.now()});}}
  async function migrateMemory(){if(smartMemory.length||!movements.length)return;for(const m of movements)await rememberMovement(m);smartMemory=await getAll('smartMemory');}
  async function saveEditedMovement(id=editingMovementId){if(!id||id!==editingMovementId)return;const existing=movements.find(x=>x.id===id);if(!existing)return;const {movement,error}=movementFromForm(existing);if(error)return toast(error);await put('movements',movement);await rememberMovement(movement);editingMovementId=null;$('movementFormTitle').textContent='Registrar movimiento';$('editBadge').hidden=true;$('cancelEditBtn').hidden=true;$('saveMovementBtn').textContent='💾 Guardar movimiento';resetMovementForm();await refresh();toast('Cambios guardados sin duplicar el registro');}

  function smartValues(field){const map=new Map();smartMemory.filter(x=>x.businessId===activeBusinessId&&x.field===field).forEach(x=>{if(!map.has(x.key))map.set(x.key,x.value)});return [...map.values()].sort((a,b)=>a.localeCompare(b,'es',{sensitivity:'base'}));}
  function smartLabel(field){return field==='category'?'Categorías guardadas':field==='concept'?'Productos / conceptos guardados':'Proveedores / clientes guardados'}
  function openSmart(field){if(!activeBusinessId)return toast('Seleccione un negocio');smartField=field;$('smartTitle').textContent=smartLabel(field);$('smartSearch').value='';renderSmartList();$('smartDialog').showModal();setTimeout(()=>$('smartSearch').focus(),50);}
  function renderSmartList(){const q=$('smartSearch').value.trim().toLocaleLowerCase('es');const values=smartValues(smartField).filter(v=>!q||v.toLocaleLowerCase('es').includes(q));$('smartList').innerHTML='';$('smartEmpty').hidden=values.length>0;values.forEach(v=>{const b=document.createElement('button');b.type='button';b.className='smart-choice';b.innerHTML=`<span>${escapeHtml(v)}</span><small>Usar</small>`;b.addEventListener('click',()=>{$(smartField).value=v;$('smartDialog').close();toast(`${v} seleccionado`);});$('smartList').appendChild(b);});}

  $('quantity').addEventListener('input',updateTotal);$('unitPrice').addEventListener('input',updateTotal);$('filterType').addEventListener('change',render);$('searchMovement').addEventListener('input',render);$('cancelEditBtn').addEventListener('click',()=>{cancelEditing(true);render()});
  document.querySelectorAll('.smart-open').forEach(b=>b.addEventListener('click',()=>openSmart(b.dataset.smart)));$('smartSearch').addEventListener('input',renderSmartList);$('closeSmartDialog').addEventListener('click',()=>$('smartDialog').close());
  $('newBusinessBtn').addEventListener('click',()=>$('businessDialog').showModal());$('closeBusinessDialog').addEventListener('click',()=>$('businessDialog').close());$('cancelBusinessBtn').addEventListener('click',()=>$('businessDialog').close());
  $('businessForm').addEventListener('submit',async e=>{e.preventDefault();const name=normalize($('businessName').value),type=normalize($('businessType').value);if(!name||!type)return;const b={id:uid('biz'),name,type,description:normalize($('businessDescription').value),createdAt:Date.now()};await put('businesses',b);activeBusinessId=b.id;$('businessForm').reset();$('businessDialog').close();await refresh();toast('Negocio creado correctamente');});
  $('movementForm').addEventListener('submit',async e=>{e.preventDefault();if(!activeBusinessId)return toast('Seleccione un negocio');if(editingMovementId)return saveEditedMovement(editingMovementId);const {movement,error}=movementFromForm();if(error)return toast(error);await put('movements',movement);await rememberMovement(movement);resetMovementForm();await refresh();toast('Movimiento guardado y memoria actualizada');});
  async function deleteMovement(id){const m=movements.find(x=>x.id===id);if(!m||!confirm(`¿Eliminar este movimiento?\n${m.concept} · ${money.format(Number(m.total||0))}`))return;await remove('movements',id);if(editingMovementId===id)cancelEditing(false);await refresh();toast('Movimiento eliminado');}
  $('deleteBusinessBtn').addEventListener('click',async()=>{const b=businesses.find(x=>x.id===activeBusinessId);if(!b)return;if(!confirm(`¿Eliminar “${b.name}” y todos sus movimientos?`))return;for(const m of businessMovements(b.id))await remove('movements',m.id);for(const mem of smartMemory.filter(x=>x.businessId===b.id))await remove('smartMemory',mem.id);await remove('businesses',b.id);activeBusinessId=null;cancelEditing(false);await refresh();toast('Negocio eliminado');});

  function reportPeriod(list){if(!list.length)return'Sin movimientos registrados';const dates=list.map(m=>m.date).filter(Boolean).sort();return dates[0]===dates[dates.length-1]?dates[0]:`${dates[0]} al ${dates[dates.length-1]}`}
  function safeName(name){return normalize(name).replace(/[^a-z0-9áéíóúñ_-]+/gi,'_').slice(0,40)||'negocio'}
  async function exportProfessionalExcel(){const b=businesses.find(x=>x.id===activeBusinessId);if(!b)return;const list=businessMovements(b.id).slice().sort((a,z)=>String(a.date).localeCompare(String(z.date)));const c=calc(list);if(!window.ExcelJS)return exportXlsxFallback(b,list,c);try{const wb=new ExcelJS.Workbook();wb.creator='MULTIGESTIÓN MR';wb.subject=`Reporte financiero y operativo - ${b.name}`;wb.created=new Date();const navy='17365D',teal='0B6B61',green='2F855A',gold='D4A017',light='EEF6F4',pale='F7FAFC',red='B42318',white='FFFFFF',gray='667085';const border={style:'thin',color:{argb:'D0D5DD'}},allBorder={top:border,left:border,bottom:border,right:border},currencyFmt='"$"#,##0.00;[Red]-"$"#,##0.00';let logoId=null;try{const src=$('brandLogo').src,base64=src.includes(',')?src.split(',')[1]:null;if(base64)logoId=wb.addImage({base64,extension:'png'});}catch(_){ }
    function setup(ws,landscape=true){ws.views=[{state:'frozen',ySplit:6,showGridLines:false}];ws.pageSetup={orientation:landscape?'landscape':'portrait',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.25,right:.25,top:.5,bottom:.5,header:.2,footer:.2}};ws.headerFooter.oddFooter='&LMULTIGESTIÓN MR&C&P de &N&RReporte generado';}
    function header(ws,subtitle){ws.mergeCells('A1:K1');const a=ws.getCell('A1');a.value='MULTIGESTIÓN MR';a.font={bold:true,size:20,color:{argb:white}};a.fill={type:'pattern',pattern:'solid',fgColor:{argb:navy}};a.alignment={horizontal:'center',vertical:'middle'};ws.getRow(1).height=32;ws.mergeCells('A2:K2');const b2=ws.getCell('A2');b2.value=b.name.toUpperCase();b2.font={bold:true,size:16,color:{argb:teal}};b2.alignment={horizontal:'center'};ws.mergeCells('A3:K3');ws.getCell('A3').value=`${b.type}${b.description?' · '+b.description:''}`;ws.getCell('A3').font={italic:true,size:11,color:{argb:gray}};ws.getCell('A3').alignment={horizontal:'center'};ws.mergeCells('A4:K4');ws.getCell('A4').value=`${subtitle} · Período: ${reportPeriod(list)}`;ws.getCell('A4').font={bold:true,size:10,color:{argb:navy}};ws.getCell('A4').alignment={horizontal:'center'};if(logoId!==null)ws.addImage(logoId,{tl:{col:.1,row:.05},ext:{width:84,height:52}});}
    function tableHeader(row){row.height=28;row.eachCell(cell=>{cell.font={bold:true,color:{argb:white}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:teal}};cell.alignment={horizontal:'center',vertical:'middle',wrapText:true};cell.border=allBorder;});}
    function addSheet(name,title,source){const ws=wb.addWorksheet(name);setup(ws,true);header(ws,title);ws.addRow([]);const heads=['Fecha','Tipo','Categoría','Producto / concepto','Cantidad','Unidad','Precio unitario','Total','Proveedor / cliente','Forma de pago','Observación'];tableHeader(ws.addRow(heads));source.forEach((m,i)=>{const row=ws.addRow([m.date,cap(m.type),m.category,m.concept,m.quantity,m.unit,m.unitPrice,m.total,m.party||'',m.paymentMethod||'',m.notes||'']);row.eachCell(cell=>{cell.border=allBorder;cell.alignment={vertical:'top',wrapText:true};});if(i%2)row.eachCell(cell=>cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:pale}});row.getCell(7).numFmt=currencyFmt;row.getCell(8).numFmt=currencyFmt;});if(!source.length){ws.mergeCells('A7:K9');ws.getCell('A7').value='Sin movimientos registrados en este apartado.';ws.getCell('A7').alignment={horizontal:'center',vertical:'middle'};ws.getCell('A7').font={italic:true,color:{argb:gray}};}ws.columns=[12,12,20,30,12,14,16,16,23,18,36].map(width=>({width}));if(source.length)ws.autoFilter={from:'A6',to:`K${6+source.length}`};}
    const ws=wb.addWorksheet('Resumen');setup(ws,false);header(ws,'Resumen financiero y operativo');ws.columns=Array(11).fill({width:18});[['A6:C6','INGRESOS'],['D6:F6','GASTOS'],['G6:I6','RESULTADO'],['J6:K6','MOVIMIENTOS']].forEach(([rg,val])=>{ws.mergeCells(rg);const c0=ws.getCell(rg.split(':')[0]);c0.value=val;c0.font={bold:true,color:{argb:white},size:11};c0.fill={type:'pattern',pattern:'solid',fgColor:{argb:teal}};c0.alignment={horizontal:'center'};});[['A7:C8',c.income],['D7:F8',c.expense],['G7:I8',c.profit],['J7:K8',list.length]].forEach(([rg,val],i)=>{ws.mergeCells(rg);const c0=ws.getCell(rg.split(':')[0]);c0.value=val;if(i<3)c0.numFmt=currencyFmt;c0.font={bold:true,size:20,color:{argb:(i===2?(c.profit<0?red:green):navy)}};c0.alignment={horizontal:'center',vertical:'middle'};c0.fill={type:'pattern',pattern:'solid',fgColor:{argb:light}};c0.border=allBorder;});ws.mergeCells('A10:K10');ws.getCell('A10').value=c.profit<0?'RESULTADO DEL PERÍODO: PÉRDIDA':c.profit>0?'RESULTADO DEL PERÍODO: GANANCIA':'RESULTADO DEL PERÍODO: SIN GANANCIA NI PÉRDIDA';ws.getCell('A10').font={bold:true,size:13,color:{argb:white}};ws.getCell('A10').fill={type:'pattern',pattern:'solid',fgColor:{argb:c.profit<0?red:c.profit>0?green:gold}};ws.getCell('A10').alignment={horizontal:'center'};ws.getCell('A12').value='Datos del proyecto';ws.getCell('A12').font={bold:true,size:13,color:{argb:navy}};[['Nombre',b.name],['Actividad',b.type],['Descripción',b.description||'—'],['Período',reportPeriod(list)],['Versión',`MULTIGESTIÓN MR V${APP_VERSION}`]].forEach((r,i)=>{const row=ws.getRow(13+i);row.getCell(1).value=r[0];row.getCell(1).font={bold:true,color:{argb:teal}};ws.mergeCells(13+i,2,13+i,7);row.getCell(2).value=r[1];row.getCell(1).border=allBorder;row.getCell(2).border=allBorder;});addSheet('Movimientos','Todos los movimientos',list);addSheet('Gastos y Compras','Detalle de gastos y compras',list.filter(isExpense));addSheet('Ingresos y Ventas','Detalle de ingresos y ventas',list.filter(isIncome));const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`MG_MR_${safeName(b.name)}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('Excel profesional generado');}catch(err){console.error(err);exportXlsxFallback(b,list,c);}}
  function exportXlsxFallback(b,list,c){if(!window.XLSX)return toast('No se pudo cargar el generador de Excel');const rows=list.map(m=>({Fecha:m.date,Tipo:cap(m.type),'Categoría':m.category,'Producto / concepto':m.concept,Cantidad:m.quantity,Unidad:m.unit,'Precio unitario':m.unitPrice,Total:m.total,'Proveedor / cliente':m.party,'Forma de pago':m.paymentMethod,'Observación':m.notes})),wb=XLSX.utils.book_new(),summary=[['MULTIGESTIÓN MR'],[b.name],[b.type],['Período',reportPeriod(list)],[],['Ingresos',c.income],['Gastos',c.expense],['Resultado',c.profit],['Movimientos',list.length]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(summary),'Resumen');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.length?rows:[{'Sin movimientos':''}]),'Movimientos');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.filter(r=>r.Tipo==='Gasto'||r.Tipo==='Compra').length?rows.filter(r=>r.Tipo==='Gasto'||r.Tipo==='Compra'):[{'Sin gastos':''}]),'Gastos y Compras');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.filter(r=>r.Tipo==='Ingreso'||r.Tipo==='Venta').length?rows.filter(r=>r.Tipo==='Ingreso'||r.Tipo==='Venta'):[{'Sin ingresos':''}]),'Ingresos y Ventas');XLSX.writeFile(wb,`MG_MR_${safeName(b.name)}.xlsx`);toast('Excel compatible generado');}
  $('exportBtn').addEventListener('click',exportProfessionalExcel);

  async function registerFreshWorker(){if(!('serviceWorker' in navigator)||!location.protocol.startsWith('http'))return;try{const regs=await navigator.serviceWorker.getRegistrations();for(const reg of regs){try{await reg.update()}catch(_){}}await navigator.serviceWorker.register('./sw.js?v=120',{updateViaCache:'none'});}catch(err){console.warn('SW',err)}}
  (async()=>{try{db=await openDB();businesses=await getAll('businesses');movements=await getAll('movements');smartMemory=await getAll('smartMemory');await migrateMemory();await refresh();registerFreshWorker();}catch(err){console.error(err);toast('No fue posible abrir la base de datos local');}})();
})();
